global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'canary-deployment'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NGINX 모니터링
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 5s
    metrics_path: /metrics

  # Legacy 애플리케이션 모니터링
  - job_name: 'legacy-apps'
    static_configs:
      - targets: 
        - 'legacy-app-1:8080'
        - 'legacy-app-2:8080'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: version
        replacement: 'legacy'

  # Refactored 애플리케이션 모니터링
  - job_name: 'refactored-apps'
    static_configs:
      - targets: 
        - 'refactored-app-1:8080'
        - 'refactored-app-2:8080'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: version
        replacement: 'refactored'

  # Alertmanager 모니터링
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # Grafana 모니터링
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Controller 서비스 모니터링
  - job_name: 'controller'
    static_configs:
      - targets: ['controller:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s